# Generated by Django 5.2.10 on 2026-01-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_workplace'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='organizations.workplace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('WORKPLACE_ADMIN', 'Workplace Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('YOUTH', 'Youth'), ('GUARDIAN', 'Guardian')], default='YOUTH', max_length=20),
        ),
    ]
