# Generated by Django 5.2.10 on 2026-01-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_workplace_logo_workplace_promo_image_and_more'),
        ('users', '0002_user_workplace_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_profiles', to='organizations.municipality'),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
