# Generated by Django 5.2.10 on 2026-01-08 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_details_job_municipality_info_and_more'),
        ('users', '0002_user_workplace_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LOTTERY', 'Entered Lottery'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESERVE', 'Reserve List')], default='PENDING', max_length=20)),
                ('priority_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.youthprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'youth')},
            },
        ),
    ]
