# Generated by Django 5.2.10 on 2026-01-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_job_dates'),
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lottery_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='lottery.jobgroup'),
        ),
    ]
