# Generated by Django 5.2.10 on 2026-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_lottery_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_grade',
            field=models.CharField(blank=True, choices=[('YEAR_1', 'Årskurs 1'), ('YEAR_2', 'Årskurs 2'), ('YEAR_3', 'Årskurs 3'), ('YEAR_4', 'Årskurs 4'), ('YEAR_5', 'Årskurs 5'), ('YEAR_6', 'Årskurs 6'), ('YEAR_7', 'Årskurs 7'), ('YEAR_8', 'Årskurs 8'), ('YEAR_9', 'Årskurs 9'), ('GYM_1', 'Gymnasiet år 1'), ('GYM_2', 'Gymnasiet år 2'), ('GYM_3', 'Gymnasiet år 3'), ('GYM_4', 'Gymnasiet år 4')], help_text='Maximum allowed grade to apply', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_grade',
            field=models.CharField(blank=True, choices=[('YEAR_1', 'Årskurs 1'), ('YEAR_2', 'Årskurs 2'), ('YEAR_3', 'Årskurs 3'), ('YEAR_4', 'Årskurs 4'), ('YEAR_5', 'Årskurs 5'), ('YEAR_6', 'Årskurs 6'), ('YEAR_7', 'Årskurs 7'), ('YEAR_8', 'Årskurs 8'), ('YEAR_9', 'Årskurs 9'), ('GYM_1', 'Gymnasiet år 1'), ('GYM_2', 'Gymnasiet år 2'), ('GYM_3', 'Gymnasiet år 3'), ('GYM_4', 'Gymnasiet år 4')], help_text='Minimum required grade to apply', max_length=20, null=True),
        ),
    ]
