# Generated by Django 5.2.10 on 2026-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_grade_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('LOTTERY', 'Lottery')], default='NORMAL', help_text='Normal jobs are always available; Lottery jobs are assigned via the lottery system', max_length=20),
        ),
    ]
