# Generated by Django 5.2.10 on 2026-01-08 14:32

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Rich text description with formatting'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero banner image (recommended: 1920x400px)', null=True, upload_to=apps.organizations.models.municipality_hero_path),
        ),
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, help_text='Municipality logo (recommended: 200x200px)', null=True, upload_to=apps.organizations.models.municipality_logo_path),
        ),
    ]
