# Generated by Django 5.2.10 on 2026-01-08 15:01

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='logo',
            field=models.ImageField(blank=True, help_text='Workplace logo (recommended: 200x200px)', null=True, upload_to=apps.organizations.models.workplace_logo_path),
        ),
        migrations.AddField(
            model_name='workplace',
            name='promo_image',
            field=models.ImageField(blank=True, help_text='Promotional image (recommended: 1200x630px)', null=True, upload_to=apps.organizations.models.workplace_promo_path),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Rich text description with formatting'),
        ),
    ]
